<div class="center">
    <a data-role="button" data-inline="true" data-icon="home" data-transition="slide" href="index.php">Home</a>
    <a data-role="button" data-inline="true" data-icon="plus" data-transition="slide" href="signup.php">Sign Up</a>
    <a data-role="button" data-inline="true" data-icon="check" data-transition="slide" href="login.php">Log In</a>
</div>
<p class="info">(You must be logged in to use this app)</p>