<div class="center">
    <a data-role="button" data-inline="true" data-icon="home" data-transition="slide" href="members.php?view=<?php echo $user; ?>">Home</a>
    <a data-role="button" data-inline="true" data-transition="slide" href="members.php">Members</a>
    <a data-role="button" data-inline="true" data-transition="slide" href="friends.php">Friends</a>
    <a data-role="button" data-inline="true" data-transition="slide" href="messages.php">Messages</a>
    <a data-role="button" data-inline="true" data-transition="slide" href="profile.php">Edit Profile</a>
    <a data-role="button" data-inline="true" data-transition="slide" href="logout.php">Log out</a>
</div>